// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type Course struct {
	ID        int64
	Name      string
	Subname   sql.NullString
	UserID    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID         string
	Name       string
	Email      string
	Password   string
	ProfileImg sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
